### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by StormingMoose** [paulidale/meccano3d#4]
The new tyre link you made is for  a 142b, a 142a can be found here https://www.thingiverse.com/thing:5021493

**Comment by paulidale** [comment]
Okay, done.  That's easier.

**Comment by StormingMoose** [comment]
Thanks.  You might like this one too.  https://www.thingiverse.com/thing:5029828 really handy for steering.

**Comment by paulidale** [comment]
Thanks for the extra part.

**Comment by StormingMoose** [comment]
Is there a link to recommend additions?  You might like this too 

https://www.thingiverse.com/thing:5187950

check my other meccano designs too please

**Comment by paulidale** [comment]
Let me know about new items.
Alternatively, I'm happy to give you write permissions so you can add things yourself.

**Comment by StormingMoose** [comment]
I can let you know through email, my inventive streak will pale for sure lol. 

The part this is missing is recommended print instructions. 

Kind Regards, 
Dave

**Comment by paulidale** [comment]
I've added the motor case.  I've a pile of these motors without case.

I'll go through your other designs as time permits.
